# Alle nodige packages laden
library(tidyverse)
library(lme4)
library(lmerTest)
library(here)
library(openxlsx2)
library(readxl)
library(inbodb)
library(sf)
library(mapview)
library(sjPlot)
library(ggeffects)
library(vegan)
library(terra)
library(qgisprocess)
library(tmap)
library(purrr)
library(sdmTMB)
library(ape)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("read_xlsx", "readxl")
conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(lmerTest::lmer)
